<a href="https://colab.research.google.com/github/isaacropero/03MIAR_ALGORITMOS_DE_OPTIMIZACION/blob/main/Algoritmos_isaac_ropero_AG1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AG1 - Actividad Guiada 1
## Isaac Ropero Mendez
### https://github.com/isaacropero/03MIAR_ALGORITMOS_DE_OPTIMIZACION

In [39]:
# Torre de Hanoi

def torre_de_hanoi(discos, origen, destino, auxiliar):
  if discos == 1:
    print(f"Mover disco {origen} a {destino}")
    return
  else:
    torre_de_hanoi(discos-1, origen, auxiliar, destino)
    print(f"Mover disco {origen} a {destino}")
    torre_de_hanoi(discos-1, auxiliar, destino, origen)

torre_de_hanoi(4, 1, 2, 3)


Mover disco 1 a 3
Mover disco 1 a 2
Mover disco 3 a 2
Mover disco 1 a 3
Mover disco 2 a 1
Mover disco 2 a 3
Mover disco 1 a 3
Mover disco 1 a 2
Mover disco 3 a 2
Mover disco 3 a 1
Mover disco 2 a 1
Mover disco 3 a 2
Mover disco 1 a 3
Mover disco 1 a 2
Mover disco 3 a 2


In [40]:
# Devolver cambio
import numpy as np

def cambio_monedas(cantidad, sistema = [25,10,5,1]):
  solucion = np.zeros(len(sistema))
  valor_acumulado = 0

  for i in range(0, len(sistema)):
    monedas = cantidad//sistema[i]

    cantidad = cantidad % sistema[i]

    solucion[i] = monedas

    if cantidad == 0:
      break

  return solucion

cambio_monedas(59)


array([2., 0., 1., 4.])

In [63]:
# Encontrar los dos puntos mas cercanos

import numpy as np

valores = np.random.randint(10000, size=10000)
print(valores)

min = np.inf
min_i = 0
min_j = 0

for i in range(0, len(valores)):
  for j in range(i+1, len(valores)):
    if np.abs(valores[i] - valores[j]) < min:
      min = np.abs(valores[i] - valores[j])
      min_i = i
      min_j = j

print(f"Distancia: {min}, valores[{min_i}]={valores[min_i]}, valores[{min_j}]={valores[min_j]}")


[5545 8950 5630 ... 7882 1332 3472]
Distancia: 0, valores[1]=8950, valores[3574]=8950


In [83]:
# Encontrar los dos puntos mas cercanos (Optimizada)

import numpy as np

valores = np.random.random(10000)
print(valores)

min = np.inf
min_index = 0

valores = np.sort(valores)
print(valores)


for i in range(1, len(valores)):
  if (valores[i] - valores[i-1]) < min:
    min = valores[i] - valores[i-1]
    min_index = i


print(f"Distancia: {min}, valores[{min_index-1}]={valores[min_index-1]}, valores[{min_index}]={valores[min_index]}")


[0.90395245 0.40959353 0.35047084 ... 0.3925802  0.00599591 0.07296284]
[8.27727750e-06 3.56911862e-05 1.40946226e-04 ... 9.99946062e-01
 9.99947599e-01 9.99975823e-01]
Distancia: 1.5236359729442484e-08, valores[5218]=0.5319064612770282, valores[5219]=0.531906476513388
